Fork flutter_v2ray 1.0.10 + fix onActivityResult NPE crash
Fix null-pointer crash in FlutterV2rayPlugin.onActivityResult that
occurred when pendingResult was null (activity/plugin recreated while
a VPN permission result was still pending, commonly triggered right
after the Android 13+ notification permission dialog).

Crash was:
java.lang.NullPointerException: Attempt to invoke interface method
'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)'
on a null object reference
  at FlutterV2rayPlugin.onActivityResult(FlutterV2rayPlugin.java:210)

Upstream: https://github.com/blueboy-tm/flutter_v2ray